# Generated by Django 6.0.7 on 2026-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=80)),
                ('world_name', models.CharField(blank=True, max_length=40)),
                ('ocid', models.CharField(max_length=120, unique=True)),
                ('character_class', models.CharField(blank=True, max_length=80)),
                ('character_level', models.PositiveIntegerField(blank=True, null=True)),
                ('character_image', models.URLField(blank=True, max_length=500)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['world_name', 'character_name'],
            },
        ),
        migrations.CreateModel(
            name='NoticeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('notice', '공지사항'), ('event', '이벤트'), ('cashshop', '캐시샵'), ('update', '업데이트')], max_length=20)),
                ('notice_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('registered_at', models.CharField(blank=True, max_length=40)),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notice_type', '-registered_at', 'title'],
                'constraints': [models.UniqueConstraint(fields=('notice_type', 'notice_id'), name='unique_notice_snapshot')],
            },
        ),
    ]
