name: maple_task_reminder
description: MapleStory homework reminder desktop app.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  desktop_multi_window: ^0.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  http: ^1.2.2
  tray_manager: ^0.5.3
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/app_icon.ico
    - assets/images/character_adele.png
    - assets/images/character_lara.png
    - assets/images/worlds/
